models.py
from app import db
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                        db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                        db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
    )


class Post(db.Model):

    # db.metadata.clear()

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
       return '<Post id: {}, Title: {}>'.format(self.id, self.title) 


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '< Tag id: {}, name: {}>'.format(self.id, self.name)

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

main.py
from app import app
from app import db

from posts.blueprint import posts

import view


app.register_blueprint(posts, url_prefix=('/blog'))

if __name__ == "__main__":
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, redirect, url_for
 
from models import Post, Tag
from .forms import PostForm

from flask import request
from app import db

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wrong')
        return redirect( url_for('posts.index') )

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}


{% block content_title %}
    New post
{% endblock %}


{% block content %}
<div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="post">
                {% for field in form %}
                <div class="form-group">
                    {{ field.label() }}
                    {{ field(class='form-control') }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Create</button>
                </form>
</div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}


{% block content_title %}
    <h1>Posts</h1>
{% endblock %}

{% block content %}
    {% for post in pages.items %}
    <p>
        <a href=" {{ url_for('posts.post_detail', slug=post.slug) }} ">{{ post.title }}</a>
    </p>
    {% endfor %}

<nav aria-label="...">
    <ul class="pagination">
        <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
        <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for page in pages.iter_pages() %}
        <li {% if page == pages.page %}
             class="page-item active" {% endif %}><a class="page-link" href="./?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}
        
        
        <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
        <a class="page-link" href="./?page={{ pages.next_num }}" tabindex="-1" aria-disabled="true">Next</a>
        </li>
    </ul>
</nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}


{% block content_title %}
    {{ post.title }}
{% endblock %}


{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-secondary">{{ tag.name }}</span></a>
        {% endfor %}
    </div>     
        {{ post.body }}
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}


{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}


{% block content %}
    {% for post in posts %}
   <div class="post">
       <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
   </div>
   {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
            {% block title %}
            {% endblock %} | Flask App
        </title>
</head>


  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href=" {{ url_for('index') }} ">FLASK</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('index') }}">Главная <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href=" {{ url_for('posts.index') }} ">Блог</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href=" {{ url_for('posts.create_post') }} ">+ New post</a>
        </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="GET">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" value="{{ request.args.get('q', '') }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    </nav>


<div class="container">

        <h1>
            {% block content_title %}
            {% endblock %}</h1>

            {% block content %}
            {% endblock %}
        
        
    
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}


{% block content_title %}
    Index Page  Home Page
{% endblock %}

{% block content %}
    Index content  Home Page
{% endblock %}